#!/bin/sh
#
# Insert co-authors into git message template
#
# This is a little less readable than I'd like, as it does a little tempfile
# shuffle.

ruby -ne 'if $_ == "{%authors%}\n" then print `git coauthors print`.chomp else puts $_ end' \
  < "$1" \
  > "$1.tmp" \
  && mv "$1.tmp" "$1"
