language: rust
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup toolchain install stable
  - rustup component add rustfmt --toolchain stable
script:
  - cargo +stable fmt -- --check
  - cargo build --verbose
  - cargo test --verbose
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
