# This is a sample build configuration for Rust.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: rustlang/rust:nightly

pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install -y cmake
          - cargo build -v
          - cargo test -v
